# GCP DevOps pipeline for GCP deployment

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - AppsOn/AWS

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(sas_token)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'

  # Validate
    - task: TerraformCLI@0
      displayName: Validate Config
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'
    
- stage: Plan
  displayName: Plan
  jobs:
  - job: plan
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(sas_token)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'

  # GCP credentials
    - task: DownloadSecureFile@1
    name: gcp-credentials # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: appson-gcp.json

  # Plan
    - task: TerraformCLI@0
      displayName: Plan Terraform Deployment
      env:
        ARM_SAS_TOKEN: $(sas_token)
        GOOGLE_APPLICATION_CREDENTIALS: $(gcp-credentials.secureFilePath)
        TF_VAR_project_id: $(project_id)
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'

# Approve
- stage: Approve
  displayName: Approve
  jobs:
  - job: approve
    displayName: Wait for approval
    pool: server
    steps: 
    - task: ManualValidation@0
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'ned@nedinthecloud.com'
        instructions: 'Review the plan in the next hour'

- stage: Apply
  displayName: Apply
  jobs:
  - job: apply
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(sas_token)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container_name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'
  
  # GCP credentials
    - task: DownloadSecureFile@1
    name: gcp-credentials # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: appson-gcp.json

  # Apply
    - task: TerraformCLI@0
      displayName: Apply Terraform Deployment
      env:
        ARM_SAS_TOKEN: $(sas_token)
        GOOGLE_APPLICATION_CREDENTIALS: $(gcp-credentials.secureFilePath)
        TF_VAR_project_id: $(project_id)
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/AppsOn/GCP'
        commandOptions: '-auto-approve'






